# Project information
site_name: IPYNBrenderer
# define TOC or order of website-
nav:
  - Home: index.md
  - APIreference: APIreference.md

site_author: nav52
site_description: >-
  A library for rendering YouTube and reference sites in Jupyter notebooks

# Repository
repo_name: nav52/IPYNBrenderer
repo_url: https://github.com/nav52/IPYNBrenderer

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/nav52

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/nav52"  target="_blank" rel="noopener">Nav</a>